[package]
name = "crony"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "3.2.21", features = ["derive"] }
colored = "2.0.0"
cron = "0.11.0"
dirs = "4.0.0"
once_cell = "1.14.0"
pomsky = "0.7.0"
pomsky-macro = "0.7.0"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tabular = "0.2.0"
