[package]
name = "crony"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
clap = { version = "3.2.21", features = ["derive"] }
colored = "2.0.0"
daemonize-me = "2.0.1"
dirs = "4.0.0"
once_cell = "1.14.0"
pomsky = "0.7.0"
pomsky-macro = "0.7.0"
rand = "0.8.5"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tabular = "0.2.0"
time = { version = "0.3.14", features = ["local-offset", "parsing", "formatting"] }
